name: deploy

on:
  workflow_dispatch: {}

jobs:

  pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      PIP_INDEX_URL: "https://:2023-04-16T23:56:46.279633Z@time-machines-pypi.sealsecurity.io/"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Package
        run: |
          pip install --upgrade build hatchling==1.14.0
          python -m build -s -w --no-isolation
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/*
          if-no-files-found: error
